# Generated by Django 5.2.7 on 2025-10-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='medium',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
