# Generated by Django 5.2.7 on 2025-10-16 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=300)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
